apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.7.5
resources:
  - upstream/argoproj/argo-cd/manifests/crds
  - upstream/argoproj/argo-cd/manifests/cluster-rbac
  - upstream/argoproj/argo-cd/manifests/base/config
  - upstream/argoproj/argo-cd/manifests/base/application-controller
  - upstream/argoproj/argo-cd/manifests/base/repo-server
  - upstream/argoproj/argo-cd/manifests/base/server
  - upstream/argoproj/argo-cd/manifests/base/redis
  - upstream/argoproj/argo-cd/manifests/base/notification
  - upstream/argoproj/argo-cd/manifests/base/applicationset-controller
patchesStrategicMerge:
  - patch-argocd-cm.yaml
  - patch-node-selectors.yaml
