apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  disable-access-log: "false"
  proxy-body-size: "0"
  use-forwarded-headers: "true"
  use-geoip: "false"
  use-gzip: "false"
  use-http2: "true"
  # use-proxy-protocol: "true"