apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-id
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/248-sh/app-id
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
