apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ingress-nginx/248-sh
    repoURL: https://github.com/248-sh/kubernetes-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
