apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: eventstore
      securityContext: {}
      containers:
        - name: eventstore
          securityContext: {}
          image: <app-image>
          imagePullPolicy: IfNotPresent
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: "All"
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: "1113"
            - name: EVENTSTORE_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: "true"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
          ports:
            - name: http
              containerPort: 2113
              protocol: TCP
            - containerPort: 1113
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/live
              port: http
          resources:
            # limits:
            #   cpu: 100m
            #   memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
