apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: esdb
images:
  - name: <app-image>
    newName: eventstore/eventstore
    newTag: "21.10.2-buster-slim"
