apiVersion: v1
kind: Service
metadata:
  name: esdb
spec:
  ports:
    - name: http
      port: 2113
      protocol: TCP
      targetPort: 2113
    - name: tcp
      port: 1113
      protocol: TCP
      targetPort: 1113
  type: ClusterIP
