sync:
  #!/usr/bin/env bash
  helm repo add dapr https://dapr.github.io/helm-charts
  helm template dapr dapr/dapr --namespace dapr-system --include-crds --version 1.9.0 -f - <<EOF > base/helm-dapr.yaml
  global:
    ha:
      enabled: true
      disruption:
        maximumUnavailable: 1
    prometheus:
      enabled: false
  dapr_placement:
    volumeclaims:
      storageClassName: longhorn
      storageSize: 1Gi
  EOF
