apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../base
  - grafana-agent-logs.yaml
  - grafana-agent-metrics.yaml
  - cadvisor-monitor.yaml
  - kube-state-metrics-monitor.yaml
  - kubelet-monitor.yaml
  - pod-logs-monitor.yaml
patchesStrategicMerge:
  - patch-grafana-agent-externalLabels.yaml
