apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --source=service
            - --source=ingress
            - --registry=txt
            - --policy=upsert-only
            - --provider=aws
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: aws-region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: aws-secret-key
