apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: cockroach-operator-
namespace: cockroach-operator-system
resources:
  - upstream/cockroachdb/cockroach-operator/config/crd
  - upstream/cockroachdb/cockroach-operator/config/rbac
  - upstream/cockroachdb/cockroach-operator/config/manager
  - upstream/cockroachdb/cockroach-operator/config/webhook
