apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/rabbitmq/cluster-operator/config/installation
patchesStrategicMerge:
  - patch-rabbitmq-operator-resources.yaml
