apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: cert-manager
spec:
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: certificate-secret
