apiVersion: v2
appVersion: "4.0.13"
description: A Helm chart for Kubernetes
name: ingress-nginx
type: application
version: 4.0.13

dependencies:
- name: ingress-nginx
  version: "4.0.13"
  repository: "https://kubernetes.github.io/ingress-nginx"
