apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - pluginConfig:
      - args:
          scoringStrategy:
            resources:
              - name: cpu
                weight: 1
            type: LeastAllocated
        name: NodeResourcesFit
