apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "248.sh"
    # service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    # service.beta.kubernetes.io/do-loadbalancer-hostname: "248.sh"
    # service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
  name: ingress-nginx-controller
  namespace: ingress-nginx
