apiVersion: descheduler/v1alpha1
kind: DeschedulerPolicy
strategies:
  LowNodeUtilization:
     enabled: false
  HighNodeUtilization:
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           cpu: 20
           memory: 20
           pods: 20
