apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.15.0
patches:
  - path: patch-deployment.yaml
