apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - patch-alertmanager-alertmanager.yaml
  - patch-prometheus-adapter-deployment.yaml
  - patch-prometheus-prometheus.yaml
