apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/yugabyte/yugabyte-operator/deploy/crds/yugabyte.com_ybclusters_crd.yaml
  - upstream/yugabyte/yugabyte-operator/deploy/operator.yaml
images:
  - name: quay.io/yugabyte/yugabytedb-operator
    newName: quay.io/yugabyte/yugabytedb-operator
    newTag: "latest"
