apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      serviceAccountName: hasura
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: hasura
                topologyKey: kubernetes.io/hostname
      containers:
        - name: hasura
          image: hasuraci/graphql-engine-pro:v2.11.3-pro.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: hasura
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            # limits:
            #   cpu: 200m
            #   memory: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
