apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: queue
  namespace: app-signals
spec:
  replicas: 1
  resources:
    # requests:
    #   cpu: 1000m
    #   memory: 2Gi
    # limits:
    #   cpu: 2000m
    #   memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi
