apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroach-pvc
  namespace: cockroach
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/component: storage
  #     app.kubernetes.io/part-of: signals
  storageClassName: retained-storage
  volumeMode: Filesystem
